M48
; DRILL file {KiCad 8.0.1} date 2024-05-05T16:57:59-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-05T16:57:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X98.7Y-106.675
X103.3Y-106.675
T2
X74.5Y-69.0
X74.5Y-114.0
X138.5Y-69.0
X138.5Y-114.0
T3
X121.69Y-101.39
X133.12Y-101.39
M30
